// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: proto/account/aggregates/example/grpc/user_resign.proto

package protoexamplegrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	grpc "vl-account/proto_generated/common/grpc"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserResignRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Base *grpc.GRPCRequest      `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Data *UserResignRequestData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *UserResignRequest) Reset() {
	*x = UserResignRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_account_aggregates_example_grpc_user_resign_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserResignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResignRequest) ProtoMessage() {}

func (x *UserResignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_account_aggregates_example_grpc_user_resign_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResignRequest.ProtoReflect.Descriptor instead.
func (*UserResignRequest) Descriptor() ([]byte, []int) {
	return file_proto_account_aggregates_example_grpc_user_resign_proto_rawDescGZIP(), []int{0}
}

func (x *UserResignRequest) GetBase() *grpc.GRPCRequest {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *UserResignRequest) GetData() *UserResignRequestData {
	if x != nil {
		return x.Data
	}
	return nil
}

type UserResignRequestData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *UserResignRequestData) Reset() {
	*x = UserResignRequestData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_account_aggregates_example_grpc_user_resign_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserResignRequestData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResignRequestData) ProtoMessage() {}

func (x *UserResignRequestData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_account_aggregates_example_grpc_user_resign_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResignRequestData.ProtoReflect.Descriptor instead.
func (*UserResignRequestData) Descriptor() ([]byte, []int) {
	return file_proto_account_aggregates_example_grpc_user_resign_proto_rawDescGZIP(), []int{1}
}

func (x *UserResignRequestData) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UserResignResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Base *grpc.GRPCResponse      `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Data *UserResignResponseData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *UserResignResponse) Reset() {
	*x = UserResignResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_account_aggregates_example_grpc_user_resign_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserResignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResignResponse) ProtoMessage() {}

func (x *UserResignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_account_aggregates_example_grpc_user_resign_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResignResponse.ProtoReflect.Descriptor instead.
func (*UserResignResponse) Descriptor() ([]byte, []int) {
	return file_proto_account_aggregates_example_grpc_user_resign_proto_rawDescGZIP(), []int{2}
}

func (x *UserResignResponse) GetBase() *grpc.GRPCResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *UserResignResponse) GetData() *UserResignResponseData {
	if x != nil {
		return x.Data
	}
	return nil
}

type UserResignResponseData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DeletedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
}

func (x *UserResignResponseData) Reset() {
	*x = UserResignResponseData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_account_aggregates_example_grpc_user_resign_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserResignResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResignResponseData) ProtoMessage() {}

func (x *UserResignResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_account_aggregates_example_grpc_user_resign_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResignResponseData.ProtoReflect.Descriptor instead.
func (*UserResignResponseData) Descriptor() ([]byte, []int) {
	return file_proto_account_aggregates_example_grpc_user_resign_proto_rawDescGZIP(), []int{3}
}

func (x *UserResignResponseData) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserResignResponseData) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

var File_proto_account_aggregates_example_grpc_user_resign_proto protoreflect.FileDescriptor

var file_proto_account_aggregates_example_grpc_user_resign_proto_rawDesc = []byte{
	0x0a, 0x37, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2f,
	0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x73, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70,
	0x6c, 0x65, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x72, 0x65, 0x73,
	0x69, 0x67, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1f, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x2e, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x65, 0x78,
	0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x1a, 0x1c, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8d, 0x01, 0x0a, 0x11, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x2c, 0x0a, 0x04, 0x62, 0x61, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x52, 0x50, 0x43,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x04, 0x62, 0x61, 0x73, 0x65, 0x12, 0x4a, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x36, 0x2e, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x73,
	0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x27, 0x0a, 0x15, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x90, 0x01, 0x0a, 0x12, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x69, 0x67,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x04, 0x62, 0x61, 0x73,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x52, 0x50, 0x43, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x52, 0x04, 0x62, 0x61, 0x73, 0x65, 0x12, 0x4b, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x37, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x2e, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x65, 0x78, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x69, 0x67, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x63, 0x0a, 0x16, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x69, 0x67, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x39, 0x0a, 0x0a, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x09, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x41, 0x74, 0x42, 0x4d, 0x5a, 0x4b, 0x76, 0x6c,
	0x2d, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x67,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x2f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x2f, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x73, 0x2f, 0x65, 0x78, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x65, 0x78,
	0x61, 0x6d, 0x70, 0x6c, 0x65, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_account_aggregates_example_grpc_user_resign_proto_rawDescOnce sync.Once
	file_proto_account_aggregates_example_grpc_user_resign_proto_rawDescData = file_proto_account_aggregates_example_grpc_user_resign_proto_rawDesc
)

func file_proto_account_aggregates_example_grpc_user_resign_proto_rawDescGZIP() []byte {
	file_proto_account_aggregates_example_grpc_user_resign_proto_rawDescOnce.Do(func() {
		file_proto_account_aggregates_example_grpc_user_resign_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_account_aggregates_example_grpc_user_resign_proto_rawDescData)
	})
	return file_proto_account_aggregates_example_grpc_user_resign_proto_rawDescData
}

var file_proto_account_aggregates_example_grpc_user_resign_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_account_aggregates_example_grpc_user_resign_proto_goTypes = []interface{}{
	(*UserResignRequest)(nil),      // 0: account.aggregates.example.grpc.UserResignRequest
	(*UserResignRequestData)(nil),  // 1: account.aggregates.example.grpc.UserResignRequestData
	(*UserResignResponse)(nil),     // 2: account.aggregates.example.grpc.UserResignResponse
	(*UserResignResponseData)(nil), // 3: account.aggregates.example.grpc.UserResignResponseData
	(*grpc.GRPCRequest)(nil),       // 4: common.grpc.GRPCRequest
	(*grpc.GRPCResponse)(nil),      // 5: common.grpc.GRPCResponse
	(*timestamppb.Timestamp)(nil),  // 6: google.protobuf.Timestamp
}
var file_proto_account_aggregates_example_grpc_user_resign_proto_depIdxs = []int32{
	4, // 0: account.aggregates.example.grpc.UserResignRequest.base:type_name -> common.grpc.GRPCRequest
	1, // 1: account.aggregates.example.grpc.UserResignRequest.data:type_name -> account.aggregates.example.grpc.UserResignRequestData
	5, // 2: account.aggregates.example.grpc.UserResignResponse.base:type_name -> common.grpc.GRPCResponse
	3, // 3: account.aggregates.example.grpc.UserResignResponse.data:type_name -> account.aggregates.example.grpc.UserResignResponseData
	6, // 4: account.aggregates.example.grpc.UserResignResponseData.deleted_at:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_account_aggregates_example_grpc_user_resign_proto_init() }
func file_proto_account_aggregates_example_grpc_user_resign_proto_init() {
	if File_proto_account_aggregates_example_grpc_user_resign_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_account_aggregates_example_grpc_user_resign_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserResignRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_account_aggregates_example_grpc_user_resign_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserResignRequestData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_account_aggregates_example_grpc_user_resign_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserResignResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_account_aggregates_example_grpc_user_resign_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserResignResponseData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_account_aggregates_example_grpc_user_resign_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_account_aggregates_example_grpc_user_resign_proto_goTypes,
		DependencyIndexes: file_proto_account_aggregates_example_grpc_user_resign_proto_depIdxs,
		MessageInfos:      file_proto_account_aggregates_example_grpc_user_resign_proto_msgTypes,
	}.Build()
	File_proto_account_aggregates_example_grpc_user_resign_proto = out.File
	file_proto_account_aggregates_example_grpc_user_resign_proto_rawDesc = nil
	file_proto_account_aggregates_example_grpc_user_resign_proto_goTypes = nil
	file_proto_account_aggregates_example_grpc_user_resign_proto_depIdxs = nil
}
