// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: proto/notification/aggregates/role_notification/role_notification_setting_delete.proto

package protorolenotification

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	grpc "vl-account/proto_generated/common/grpc"
	messaging "vl-account/proto_generated/common/messaging"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoleNotificationSettingDeleteRequestData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrganizationId       uint64 `protobuf:"varint,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	OrganizationalRoleId uint64 `protobuf:"varint,2,opt,name=organizational_role_id,json=organizationalRoleId,proto3" json:"organizational_role_id,omitempty"`
}

func (x *RoleNotificationSettingDeleteRequestData) Reset() {
	*x = RoleNotificationSettingDeleteRequestData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_notification_aggregates_role_notification_role_notification_setting_delete_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleNotificationSettingDeleteRequestData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleNotificationSettingDeleteRequestData) ProtoMessage() {}

func (x *RoleNotificationSettingDeleteRequestData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_aggregates_role_notification_role_notification_setting_delete_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleNotificationSettingDeleteRequestData.ProtoReflect.Descriptor instead.
func (*RoleNotificationSettingDeleteRequestData) Descriptor() ([]byte, []int) {
	return file_proto_notification_aggregates_role_notification_role_notification_setting_delete_proto_rawDescGZIP(), []int{0}
}

func (x *RoleNotificationSettingDeleteRequestData) GetOrganizationId() uint64 {
	if x != nil {
		return x.OrganizationId
	}
	return 0
}

func (x *RoleNotificationSettingDeleteRequestData) GetOrganizationalRoleId() uint64 {
	if x != nil {
		return x.OrganizationalRoleId
	}
	return 0
}

type RoleNotificationSettingDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Base *grpc.GRPCRequest                         `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Data *RoleNotificationSettingDeleteRequestData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *RoleNotificationSettingDeleteRequest) Reset() {
	*x = RoleNotificationSettingDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_notification_aggregates_role_notification_role_notification_setting_delete_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleNotificationSettingDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleNotificationSettingDeleteRequest) ProtoMessage() {}

func (x *RoleNotificationSettingDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_aggregates_role_notification_role_notification_setting_delete_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleNotificationSettingDeleteRequest.ProtoReflect.Descriptor instead.
func (*RoleNotificationSettingDeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_notification_aggregates_role_notification_role_notification_setting_delete_proto_rawDescGZIP(), []int{1}
}

func (x *RoleNotificationSettingDeleteRequest) GetBase() *grpc.GRPCRequest {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *RoleNotificationSettingDeleteRequest) GetData() *RoleNotificationSettingDeleteRequestData {
	if x != nil {
		return x.Data
	}
	return nil
}

type RoleNotificationSettingDeleteResponseData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrganizationId       uint64 `protobuf:"varint,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	OrganizationalRoleId uint64 `protobuf:"varint,2,opt,name=organizational_role_id,json=organizationalRoleId,proto3" json:"organizational_role_id,omitempty"`
}

func (x *RoleNotificationSettingDeleteResponseData) Reset() {
	*x = RoleNotificationSettingDeleteResponseData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_notification_aggregates_role_notification_role_notification_setting_delete_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleNotificationSettingDeleteResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleNotificationSettingDeleteResponseData) ProtoMessage() {}

func (x *RoleNotificationSettingDeleteResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_aggregates_role_notification_role_notification_setting_delete_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleNotificationSettingDeleteResponseData.ProtoReflect.Descriptor instead.
func (*RoleNotificationSettingDeleteResponseData) Descriptor() ([]byte, []int) {
	return file_proto_notification_aggregates_role_notification_role_notification_setting_delete_proto_rawDescGZIP(), []int{2}
}

func (x *RoleNotificationSettingDeleteResponseData) GetOrganizationId() uint64 {
	if x != nil {
		return x.OrganizationId
	}
	return 0
}

func (x *RoleNotificationSettingDeleteResponseData) GetOrganizationalRoleId() uint64 {
	if x != nil {
		return x.OrganizationalRoleId
	}
	return 0
}

type RoleNotificationSettingDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Base *grpc.GRPCResponse                         `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Data *RoleNotificationSettingDeleteResponseData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *RoleNotificationSettingDeleteResponse) Reset() {
	*x = RoleNotificationSettingDeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_notification_aggregates_role_notification_role_notification_setting_delete_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleNotificationSettingDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleNotificationSettingDeleteResponse) ProtoMessage() {}

func (x *RoleNotificationSettingDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_aggregates_role_notification_role_notification_setting_delete_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleNotificationSettingDeleteResponse.ProtoReflect.Descriptor instead.
func (*RoleNotificationSettingDeleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_notification_aggregates_role_notification_role_notification_setting_delete_proto_rawDescGZIP(), []int{3}
}

func (x *RoleNotificationSettingDeleteResponse) GetBase() *grpc.GRPCResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *RoleNotificationSettingDeleteResponse) GetData() *RoleNotificationSettingDeleteResponseData {
	if x != nil {
		return x.Data
	}
	return nil
}

type RoleNotificationSettingDeleteUseCaseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Transaction *messaging.Transaction                    `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	Client      *messaging.Client                         `protobuf:"bytes,2,opt,name=client,proto3" json:"client,omitempty"`
	Data        *RoleNotificationSettingDeleteRequestData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *RoleNotificationSettingDeleteUseCaseRequest) Reset() {
	*x = RoleNotificationSettingDeleteUseCaseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_notification_aggregates_role_notification_role_notification_setting_delete_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleNotificationSettingDeleteUseCaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleNotificationSettingDeleteUseCaseRequest) ProtoMessage() {}

func (x *RoleNotificationSettingDeleteUseCaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_aggregates_role_notification_role_notification_setting_delete_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleNotificationSettingDeleteUseCaseRequest.ProtoReflect.Descriptor instead.
func (*RoleNotificationSettingDeleteUseCaseRequest) Descriptor() ([]byte, []int) {
	return file_proto_notification_aggregates_role_notification_role_notification_setting_delete_proto_rawDescGZIP(), []int{4}
}

func (x *RoleNotificationSettingDeleteUseCaseRequest) GetTransaction() *messaging.Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *RoleNotificationSettingDeleteUseCaseRequest) GetClient() *messaging.Client {
	if x != nil {
		return x.Client
	}
	return nil
}

func (x *RoleNotificationSettingDeleteUseCaseRequest) GetData() *RoleNotificationSettingDeleteRequestData {
	if x != nil {
		return x.Data
	}
	return nil
}

type RoleNotificationSettingDeleteUseCaseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Transaction *messaging.Transaction                     `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	Error       *messaging.Error                           `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Data        *RoleNotificationSettingDeleteResponseData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *RoleNotificationSettingDeleteUseCaseResponse) Reset() {
	*x = RoleNotificationSettingDeleteUseCaseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_notification_aggregates_role_notification_role_notification_setting_delete_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleNotificationSettingDeleteUseCaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleNotificationSettingDeleteUseCaseResponse) ProtoMessage() {}

func (x *RoleNotificationSettingDeleteUseCaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_aggregates_role_notification_role_notification_setting_delete_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleNotificationSettingDeleteUseCaseResponse.ProtoReflect.Descriptor instead.
func (*RoleNotificationSettingDeleteUseCaseResponse) Descriptor() ([]byte, []int) {
	return file_proto_notification_aggregates_role_notification_role_notification_setting_delete_proto_rawDescGZIP(), []int{5}
}

func (x *RoleNotificationSettingDeleteUseCaseResponse) GetTransaction() *messaging.Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *RoleNotificationSettingDeleteUseCaseResponse) GetError() *messaging.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *RoleNotificationSettingDeleteUseCaseResponse) GetData() *RoleNotificationSettingDeleteResponseData {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_notification_aggregates_role_notification_role_notification_setting_delete_proto protoreflect.FileDescriptor

var file_proto_notification_aggregates_role_notification_role_notification_setting_delete_proto_rawDesc = []byte{
	0x0a, 0x56, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x73, 0x2f,
	0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2f, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x64, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x29, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65,
	0x73, 0x2e, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x1a, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x26, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x89, 0x01, 0x0a, 0x28, 0x52, 0x6f,
	0x6c, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65,
	0x74, 0x74, 0x69, 0x6e, 0x67, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x27, 0x0a, 0x0f, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69,
	0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x0e, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12,
	0x34, 0x0a, 0x16, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x61,
	0x6c, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x14, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x52,
	0x6f, 0x6c, 0x65, 0x49, 0x64, 0x22, 0xbd, 0x01, 0x0a, 0x24, 0x52, 0x6f, 0x6c, 0x65, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e,
	0x67, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c,
	0x0a, 0x04, 0x62, 0x61, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x52, 0x50, 0x43, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x04, 0x62, 0x61, 0x73, 0x65, 0x12, 0x67, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x53, 0x2e, 0x6e, 0x6f, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67,
	0x61, 0x74, 0x65, 0x73, 0x2e, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x8a, 0x01, 0x0a, 0x29, 0x52, 0x6f, 0x6c, 0x65, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e,
	0x67, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x27, 0x0a, 0x0f, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x6f, 0x72,
	0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x34, 0x0a, 0x16,
	0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x72,
	0x6f, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x14, 0x6f, 0x72,
	0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x52, 0x6f, 0x6c, 0x65,
	0x49, 0x64, 0x22, 0xc0, 0x01, 0x0a, 0x25, 0x52, 0x6f, 0x6c, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x04,
	0x62, 0x61, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x52, 0x50, 0x43, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x04, 0x62, 0x61, 0x73, 0x65, 0x12, 0x68, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x54, 0x2e, 0x6e, 0x6f, 0x74, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61,
	0x74, 0x65, 0x73, 0x2e, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x89, 0x02, 0x0a, 0x2b, 0x52, 0x6f, 0x6c, 0x65, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e,
	0x67, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x43, 0x61, 0x73, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3f, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x2e, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x30, 0x0a, 0x06, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x52, 0x06, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x67, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x53, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x73,
	0x2e, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x22, 0x88, 0x02, 0x0a, 0x2c, 0x52, 0x6f, 0x6c, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x43, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x3f, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x2d, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x69, 0x6e, 0x67, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x12, 0x68, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x54, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x72, 0x6f, 0x6c, 0x65, 0x5f,
	0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x6f, 0x6c,
	0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x74,
	0x74, 0x69, 0x6e, 0x67, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x5d, 0x5a, 0x5b,
	0x76, 0x6c, 0x2d, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x5f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74,
	0x65, 0x73, 0x2f, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x72, 0x6f, 0x6c, 0x65, 0x6e,
	0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_notification_aggregates_role_notification_role_notification_setting_delete_proto_rawDescOnce sync.Once
	file_proto_notification_aggregates_role_notification_role_notification_setting_delete_proto_rawDescData = file_proto_notification_aggregates_role_notification_role_notification_setting_delete_proto_rawDesc
)

func file_proto_notification_aggregates_role_notification_role_notification_setting_delete_proto_rawDescGZIP() []byte {
	file_proto_notification_aggregates_role_notification_role_notification_setting_delete_proto_rawDescOnce.Do(func() {
		file_proto_notification_aggregates_role_notification_role_notification_setting_delete_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_notification_aggregates_role_notification_role_notification_setting_delete_proto_rawDescData)
	})
	return file_proto_notification_aggregates_role_notification_role_notification_setting_delete_proto_rawDescData
}

var file_proto_notification_aggregates_role_notification_role_notification_setting_delete_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_notification_aggregates_role_notification_role_notification_setting_delete_proto_goTypes = []interface{}{
	(*RoleNotificationSettingDeleteRequestData)(nil),     // 0: notification.aggregates.role_notification.RoleNotificationSettingDeleteRequestData
	(*RoleNotificationSettingDeleteRequest)(nil),         // 1: notification.aggregates.role_notification.RoleNotificationSettingDeleteRequest
	(*RoleNotificationSettingDeleteResponseData)(nil),    // 2: notification.aggregates.role_notification.RoleNotificationSettingDeleteResponseData
	(*RoleNotificationSettingDeleteResponse)(nil),        // 3: notification.aggregates.role_notification.RoleNotificationSettingDeleteResponse
	(*RoleNotificationSettingDeleteUseCaseRequest)(nil),  // 4: notification.aggregates.role_notification.RoleNotificationSettingDeleteUseCaseRequest
	(*RoleNotificationSettingDeleteUseCaseResponse)(nil), // 5: notification.aggregates.role_notification.RoleNotificationSettingDeleteUseCaseResponse
	(*grpc.GRPCRequest)(nil),                             // 6: common.grpc.GRPCRequest
	(*grpc.GRPCResponse)(nil),                            // 7: common.grpc.GRPCResponse
	(*messaging.Transaction)(nil),                        // 8: common.messaging.Transaction
	(*messaging.Client)(nil),                             // 9: common.messaging.Client
	(*messaging.Error)(nil),                              // 10: common.messaging.Error
}
var file_proto_notification_aggregates_role_notification_role_notification_setting_delete_proto_depIdxs = []int32{
	6,  // 0: notification.aggregates.role_notification.RoleNotificationSettingDeleteRequest.base:type_name -> common.grpc.GRPCRequest
	0,  // 1: notification.aggregates.role_notification.RoleNotificationSettingDeleteRequest.data:type_name -> notification.aggregates.role_notification.RoleNotificationSettingDeleteRequestData
	7,  // 2: notification.aggregates.role_notification.RoleNotificationSettingDeleteResponse.base:type_name -> common.grpc.GRPCResponse
	2,  // 3: notification.aggregates.role_notification.RoleNotificationSettingDeleteResponse.data:type_name -> notification.aggregates.role_notification.RoleNotificationSettingDeleteResponseData
	8,  // 4: notification.aggregates.role_notification.RoleNotificationSettingDeleteUseCaseRequest.transaction:type_name -> common.messaging.Transaction
	9,  // 5: notification.aggregates.role_notification.RoleNotificationSettingDeleteUseCaseRequest.client:type_name -> common.messaging.Client
	0,  // 6: notification.aggregates.role_notification.RoleNotificationSettingDeleteUseCaseRequest.data:type_name -> notification.aggregates.role_notification.RoleNotificationSettingDeleteRequestData
	8,  // 7: notification.aggregates.role_notification.RoleNotificationSettingDeleteUseCaseResponse.transaction:type_name -> common.messaging.Transaction
	10, // 8: notification.aggregates.role_notification.RoleNotificationSettingDeleteUseCaseResponse.error:type_name -> common.messaging.Error
	2,  // 9: notification.aggregates.role_notification.RoleNotificationSettingDeleteUseCaseResponse.data:type_name -> notification.aggregates.role_notification.RoleNotificationSettingDeleteResponseData
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() {
	file_proto_notification_aggregates_role_notification_role_notification_setting_delete_proto_init()
}
func file_proto_notification_aggregates_role_notification_role_notification_setting_delete_proto_init() {
	if File_proto_notification_aggregates_role_notification_role_notification_setting_delete_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_notification_aggregates_role_notification_role_notification_setting_delete_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleNotificationSettingDeleteRequestData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_notification_aggregates_role_notification_role_notification_setting_delete_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleNotificationSettingDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_notification_aggregates_role_notification_role_notification_setting_delete_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleNotificationSettingDeleteResponseData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_notification_aggregates_role_notification_role_notification_setting_delete_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleNotificationSettingDeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_notification_aggregates_role_notification_role_notification_setting_delete_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleNotificationSettingDeleteUseCaseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_notification_aggregates_role_notification_role_notification_setting_delete_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleNotificationSettingDeleteUseCaseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_notification_aggregates_role_notification_role_notification_setting_delete_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_notification_aggregates_role_notification_role_notification_setting_delete_proto_goTypes,
		DependencyIndexes: file_proto_notification_aggregates_role_notification_role_notification_setting_delete_proto_depIdxs,
		MessageInfos:      file_proto_notification_aggregates_role_notification_role_notification_setting_delete_proto_msgTypes,
	}.Build()
	File_proto_notification_aggregates_role_notification_role_notification_setting_delete_proto = out.File
	file_proto_notification_aggregates_role_notification_role_notification_setting_delete_proto_rawDesc = nil
	file_proto_notification_aggregates_role_notification_role_notification_setting_delete_proto_goTypes = nil
	file_proto_notification_aggregates_role_notification_role_notification_setting_delete_proto_depIdxs = nil
}
