// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: proto/notification/aggregates/role_notification/role_notification_setting_finalizing.proto

package protorolenotification

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	messaging "vl-account/proto_generated/common/messaging"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Use Case
type RoleNotificationSettingFinalizingUseCaseRequestData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RoleNotificationSettingFinalizingUseCaseRequestData) Reset() {
	*x = RoleNotificationSettingFinalizingUseCaseRequestData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_notification_aggregates_role_notification_role_notification_setting_finalizing_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleNotificationSettingFinalizingUseCaseRequestData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleNotificationSettingFinalizingUseCaseRequestData) ProtoMessage() {}

func (x *RoleNotificationSettingFinalizingUseCaseRequestData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_aggregates_role_notification_role_notification_setting_finalizing_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleNotificationSettingFinalizingUseCaseRequestData.ProtoReflect.Descriptor instead.
func (*RoleNotificationSettingFinalizingUseCaseRequestData) Descriptor() ([]byte, []int) {
	return file_proto_notification_aggregates_role_notification_role_notification_setting_finalizing_proto_rawDescGZIP(), []int{0}
}

func (x *RoleNotificationSettingFinalizingUseCaseRequestData) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RoleNotificationSettingFinalizingUseCaseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Transaction *messaging.Transaction                               `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	Client      *messaging.Client                                    `protobuf:"bytes,2,opt,name=client,proto3" json:"client,omitempty"`
	Data        *RoleNotificationSettingFinalizingUseCaseRequestData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *RoleNotificationSettingFinalizingUseCaseRequest) Reset() {
	*x = RoleNotificationSettingFinalizingUseCaseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_notification_aggregates_role_notification_role_notification_setting_finalizing_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleNotificationSettingFinalizingUseCaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleNotificationSettingFinalizingUseCaseRequest) ProtoMessage() {}

func (x *RoleNotificationSettingFinalizingUseCaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_aggregates_role_notification_role_notification_setting_finalizing_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleNotificationSettingFinalizingUseCaseRequest.ProtoReflect.Descriptor instead.
func (*RoleNotificationSettingFinalizingUseCaseRequest) Descriptor() ([]byte, []int) {
	return file_proto_notification_aggregates_role_notification_role_notification_setting_finalizing_proto_rawDescGZIP(), []int{1}
}

func (x *RoleNotificationSettingFinalizingUseCaseRequest) GetTransaction() *messaging.Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *RoleNotificationSettingFinalizingUseCaseRequest) GetClient() *messaging.Client {
	if x != nil {
		return x.Client
	}
	return nil
}

func (x *RoleNotificationSettingFinalizingUseCaseRequest) GetData() *RoleNotificationSettingFinalizingUseCaseRequestData {
	if x != nil {
		return x.Data
	}
	return nil
}

type RoleNotificationSettingFinalizingUseCaseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Transaction *messaging.Transaction `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	Error       *messaging.Error       `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *RoleNotificationSettingFinalizingUseCaseResponse) Reset() {
	*x = RoleNotificationSettingFinalizingUseCaseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_notification_aggregates_role_notification_role_notification_setting_finalizing_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleNotificationSettingFinalizingUseCaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleNotificationSettingFinalizingUseCaseResponse) ProtoMessage() {}

func (x *RoleNotificationSettingFinalizingUseCaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_aggregates_role_notification_role_notification_setting_finalizing_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleNotificationSettingFinalizingUseCaseResponse.ProtoReflect.Descriptor instead.
func (*RoleNotificationSettingFinalizingUseCaseResponse) Descriptor() ([]byte, []int) {
	return file_proto_notification_aggregates_role_notification_role_notification_setting_finalizing_proto_rawDescGZIP(), []int{2}
}

func (x *RoleNotificationSettingFinalizingUseCaseResponse) GetTransaction() *messaging.Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *RoleNotificationSettingFinalizingUseCaseResponse) GetError() *messaging.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// CQRS
type RoleNotificationSettingFinalizingCQRSRequestData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RoleNotificationSettingFinalizingCQRSRequestData) Reset() {
	*x = RoleNotificationSettingFinalizingCQRSRequestData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_notification_aggregates_role_notification_role_notification_setting_finalizing_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleNotificationSettingFinalizingCQRSRequestData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleNotificationSettingFinalizingCQRSRequestData) ProtoMessage() {}

func (x *RoleNotificationSettingFinalizingCQRSRequestData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_aggregates_role_notification_role_notification_setting_finalizing_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleNotificationSettingFinalizingCQRSRequestData.ProtoReflect.Descriptor instead.
func (*RoleNotificationSettingFinalizingCQRSRequestData) Descriptor() ([]byte, []int) {
	return file_proto_notification_aggregates_role_notification_role_notification_setting_finalizing_proto_rawDescGZIP(), []int{3}
}

func (x *RoleNotificationSettingFinalizingCQRSRequestData) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RoleNotificationSettingFinalizingCQRSRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Transaction *messaging.Transaction                            `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	Client      *messaging.Client                                 `protobuf:"bytes,2,opt,name=client,proto3" json:"client,omitempty"`
	Data        *RoleNotificationSettingFinalizingCQRSRequestData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *RoleNotificationSettingFinalizingCQRSRequest) Reset() {
	*x = RoleNotificationSettingFinalizingCQRSRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_notification_aggregates_role_notification_role_notification_setting_finalizing_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleNotificationSettingFinalizingCQRSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleNotificationSettingFinalizingCQRSRequest) ProtoMessage() {}

func (x *RoleNotificationSettingFinalizingCQRSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_aggregates_role_notification_role_notification_setting_finalizing_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleNotificationSettingFinalizingCQRSRequest.ProtoReflect.Descriptor instead.
func (*RoleNotificationSettingFinalizingCQRSRequest) Descriptor() ([]byte, []int) {
	return file_proto_notification_aggregates_role_notification_role_notification_setting_finalizing_proto_rawDescGZIP(), []int{4}
}

func (x *RoleNotificationSettingFinalizingCQRSRequest) GetTransaction() *messaging.Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *RoleNotificationSettingFinalizingCQRSRequest) GetClient() *messaging.Client {
	if x != nil {
		return x.Client
	}
	return nil
}

func (x *RoleNotificationSettingFinalizingCQRSRequest) GetData() *RoleNotificationSettingFinalizingCQRSRequestData {
	if x != nil {
		return x.Data
	}
	return nil
}

type RoleNotificationSettingFinalizingCQRSResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Transaction *messaging.Transaction   `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	Error       *messaging.Error         `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Data        *RoleNotificationSetting `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *RoleNotificationSettingFinalizingCQRSResponse) Reset() {
	*x = RoleNotificationSettingFinalizingCQRSResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_notification_aggregates_role_notification_role_notification_setting_finalizing_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleNotificationSettingFinalizingCQRSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleNotificationSettingFinalizingCQRSResponse) ProtoMessage() {}

func (x *RoleNotificationSettingFinalizingCQRSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_aggregates_role_notification_role_notification_setting_finalizing_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleNotificationSettingFinalizingCQRSResponse.ProtoReflect.Descriptor instead.
func (*RoleNotificationSettingFinalizingCQRSResponse) Descriptor() ([]byte, []int) {
	return file_proto_notification_aggregates_role_notification_role_notification_setting_finalizing_proto_rawDescGZIP(), []int{5}
}

func (x *RoleNotificationSettingFinalizingCQRSResponse) GetTransaction() *messaging.Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *RoleNotificationSettingFinalizingCQRSResponse) GetError() *messaging.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *RoleNotificationSettingFinalizingCQRSResponse) GetData() *RoleNotificationSetting {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_notification_aggregates_role_notification_role_notification_setting_finalizing_proto protoreflect.FileDescriptor

var file_proto_notification_aggregates_role_notification_role_notification_setting_finalizing_proto_rawDesc = []byte{
	0x0a, 0x5a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x73, 0x2f,
	0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2f, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x66, 0x69, 0x6e, 0x61,
	0x6c, 0x69, 0x7a, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x29, 0x6e, 0x6f,
	0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x61, 0x67, 0x67, 0x72, 0x65,
	0x67, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x6e, 0x6f, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x4f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6e,
	0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x61, 0x67, 0x67, 0x72,
	0x65, 0x67, 0x61, 0x74, 0x65, 0x73, 0x2f, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x6e, 0x6f, 0x74, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x6e, 0x6f,
	0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x65, 0x74, 0x74, 0x69,
	0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x26, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67,
	0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x45, 0x0a, 0x33, 0x52, 0x6f, 0x6c, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x46, 0x69, 0x6e, 0x61, 0x6c,
	0x69, 0x7a, 0x69, 0x6e, 0x67, 0x55, 0x73, 0x65, 0x43, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x98, 0x02, 0x0a, 0x2f, 0x52, 0x6f, 0x6c, 0x65,
	0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x74, 0x74,
	0x69, 0x6e, 0x67, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x69, 0x6e, 0x67, 0x55, 0x73, 0x65,
	0x43, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3f, 0x0a, 0x0b, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1d, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x69, 0x6e, 0x67, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x30, 0x0a, 0x06,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x2e,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x06, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x72,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x5e, 0x2e, 0x6e,
	0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x61, 0x67, 0x67, 0x72,
	0x65, 0x67, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x6e, 0x6f, 0x74, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x4e, 0x6f, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67,
	0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x69, 0x6e, 0x67, 0x55, 0x73, 0x65, 0x43, 0x61, 0x73,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0xa2, 0x01, 0x0a, 0x30, 0x52, 0x6f, 0x6c, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x46, 0x69,
	0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x69, 0x6e, 0x67, 0x55, 0x73, 0x65, 0x43, 0x61, 0x73, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x2e,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2d, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x42, 0x0a, 0x30, 0x52, 0x6f, 0x6c, 0x65, 0x4e,
	0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x74, 0x74, 0x69,
	0x6e, 0x67, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x69, 0x6e, 0x67, 0x43, 0x51, 0x52, 0x53,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x92, 0x02, 0x0a, 0x2c,
	0x52, 0x6f, 0x6c, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x69, 0x6e,
	0x67, 0x43, 0x51, 0x52, 0x53, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3f, 0x0a, 0x0b,
	0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1d, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x69, 0x6e, 0x67, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x30, 0x0a,
	0x06, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67,
	0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x06, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12,
	0x6f, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x5b, 0x2e,
	0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x61, 0x67, 0x67,
	0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x6e, 0x6f, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e,
	0x67, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x69, 0x6e, 0x67, 0x43, 0x51, 0x52, 0x53, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x22, 0xf7, 0x01, 0x0a, 0x2d, 0x52, 0x6f, 0x6c, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x46, 0x69, 0x6e, 0x61,
	0x6c, 0x69, 0x7a, 0x69, 0x6e, 0x67, 0x43, 0x51, 0x52, 0x53, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x3f, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x2d, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x69, 0x6e, 0x67, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x12, 0x56, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x42, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x72, 0x6f, 0x6c, 0x65, 0x5f,
	0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x6f, 0x6c,
	0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x74,
	0x74, 0x69, 0x6e, 0x67, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x5d, 0x5a, 0x5b, 0x76, 0x6c,
	0x2d, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x67,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x73,
	0x2f, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x72, 0x6f, 0x6c, 0x65, 0x6e, 0x6f, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_notification_aggregates_role_notification_role_notification_setting_finalizing_proto_rawDescOnce sync.Once
	file_proto_notification_aggregates_role_notification_role_notification_setting_finalizing_proto_rawDescData = file_proto_notification_aggregates_role_notification_role_notification_setting_finalizing_proto_rawDesc
)

func file_proto_notification_aggregates_role_notification_role_notification_setting_finalizing_proto_rawDescGZIP() []byte {
	file_proto_notification_aggregates_role_notification_role_notification_setting_finalizing_proto_rawDescOnce.Do(func() {
		file_proto_notification_aggregates_role_notification_role_notification_setting_finalizing_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_notification_aggregates_role_notification_role_notification_setting_finalizing_proto_rawDescData)
	})
	return file_proto_notification_aggregates_role_notification_role_notification_setting_finalizing_proto_rawDescData
}

var file_proto_notification_aggregates_role_notification_role_notification_setting_finalizing_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_notification_aggregates_role_notification_role_notification_setting_finalizing_proto_goTypes = []interface{}{
	(*RoleNotificationSettingFinalizingUseCaseRequestData)(nil), // 0: notification.aggregates.role_notification.RoleNotificationSettingFinalizingUseCaseRequestData
	(*RoleNotificationSettingFinalizingUseCaseRequest)(nil),     // 1: notification.aggregates.role_notification.RoleNotificationSettingFinalizingUseCaseRequest
	(*RoleNotificationSettingFinalizingUseCaseResponse)(nil),    // 2: notification.aggregates.role_notification.RoleNotificationSettingFinalizingUseCaseResponse
	(*RoleNotificationSettingFinalizingCQRSRequestData)(nil),    // 3: notification.aggregates.role_notification.RoleNotificationSettingFinalizingCQRSRequestData
	(*RoleNotificationSettingFinalizingCQRSRequest)(nil),        // 4: notification.aggregates.role_notification.RoleNotificationSettingFinalizingCQRSRequest
	(*RoleNotificationSettingFinalizingCQRSResponse)(nil),       // 5: notification.aggregates.role_notification.RoleNotificationSettingFinalizingCQRSResponse
	(*messaging.Transaction)(nil),                               // 6: common.messaging.Transaction
	(*messaging.Client)(nil),                                    // 7: common.messaging.Client
	(*messaging.Error)(nil),                                     // 8: common.messaging.Error
	(*RoleNotificationSetting)(nil),                             // 9: notification.aggregates.role_notification.RoleNotificationSetting
}
var file_proto_notification_aggregates_role_notification_role_notification_setting_finalizing_proto_depIdxs = []int32{
	6,  // 0: notification.aggregates.role_notification.RoleNotificationSettingFinalizingUseCaseRequest.transaction:type_name -> common.messaging.Transaction
	7,  // 1: notification.aggregates.role_notification.RoleNotificationSettingFinalizingUseCaseRequest.client:type_name -> common.messaging.Client
	0,  // 2: notification.aggregates.role_notification.RoleNotificationSettingFinalizingUseCaseRequest.data:type_name -> notification.aggregates.role_notification.RoleNotificationSettingFinalizingUseCaseRequestData
	6,  // 3: notification.aggregates.role_notification.RoleNotificationSettingFinalizingUseCaseResponse.transaction:type_name -> common.messaging.Transaction
	8,  // 4: notification.aggregates.role_notification.RoleNotificationSettingFinalizingUseCaseResponse.error:type_name -> common.messaging.Error
	6,  // 5: notification.aggregates.role_notification.RoleNotificationSettingFinalizingCQRSRequest.transaction:type_name -> common.messaging.Transaction
	7,  // 6: notification.aggregates.role_notification.RoleNotificationSettingFinalizingCQRSRequest.client:type_name -> common.messaging.Client
	3,  // 7: notification.aggregates.role_notification.RoleNotificationSettingFinalizingCQRSRequest.data:type_name -> notification.aggregates.role_notification.RoleNotificationSettingFinalizingCQRSRequestData
	6,  // 8: notification.aggregates.role_notification.RoleNotificationSettingFinalizingCQRSResponse.transaction:type_name -> common.messaging.Transaction
	8,  // 9: notification.aggregates.role_notification.RoleNotificationSettingFinalizingCQRSResponse.error:type_name -> common.messaging.Error
	9,  // 10: notification.aggregates.role_notification.RoleNotificationSettingFinalizingCQRSResponse.data:type_name -> notification.aggregates.role_notification.RoleNotificationSetting
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() {
	file_proto_notification_aggregates_role_notification_role_notification_setting_finalizing_proto_init()
}
func file_proto_notification_aggregates_role_notification_role_notification_setting_finalizing_proto_init() {
	if File_proto_notification_aggregates_role_notification_role_notification_setting_finalizing_proto != nil {
		return
	}
	file_proto_notification_aggregates_role_notification_role_notification_setting_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_notification_aggregates_role_notification_role_notification_setting_finalizing_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleNotificationSettingFinalizingUseCaseRequestData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_notification_aggregates_role_notification_role_notification_setting_finalizing_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleNotificationSettingFinalizingUseCaseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_notification_aggregates_role_notification_role_notification_setting_finalizing_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleNotificationSettingFinalizingUseCaseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_notification_aggregates_role_notification_role_notification_setting_finalizing_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleNotificationSettingFinalizingCQRSRequestData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_notification_aggregates_role_notification_role_notification_setting_finalizing_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleNotificationSettingFinalizingCQRSRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_notification_aggregates_role_notification_role_notification_setting_finalizing_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleNotificationSettingFinalizingCQRSResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_notification_aggregates_role_notification_role_notification_setting_finalizing_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_notification_aggregates_role_notification_role_notification_setting_finalizing_proto_goTypes,
		DependencyIndexes: file_proto_notification_aggregates_role_notification_role_notification_setting_finalizing_proto_depIdxs,
		MessageInfos:      file_proto_notification_aggregates_role_notification_role_notification_setting_finalizing_proto_msgTypes,
	}.Build()
	File_proto_notification_aggregates_role_notification_role_notification_setting_finalizing_proto = out.File
	file_proto_notification_aggregates_role_notification_role_notification_setting_finalizing_proto_rawDesc = nil
	file_proto_notification_aggregates_role_notification_role_notification_setting_finalizing_proto_goTypes = nil
	file_proto_notification_aggregates_role_notification_role_notification_setting_finalizing_proto_depIdxs = nil
}
